ALTER TABLE "Medication" ADD COLUMN "doseAmount" DOUBLE PRECISION;
ALTER TABLE "Medication" ADD COLUMN "doseUnit" TEXT;
ALTER TABLE "Medication" ADD COLUMN "isPrn" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Medication" ADD COLUMN "frequency" TEXT NOT NULL DEFAULT 'DAILY';
ALTER TABLE "Medication" ADD COLUMN "frequencyDays" INTEGER[] NOT NULL DEFAULT ARRAY[]::INTEGER[];
ALTER TABLE "Medication" ADD COLUMN "indication" TEXT;
ALTER TABLE "Medication" ADD COLUMN "appearance" TEXT;
ALTER TABLE "Medication" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
